services:
    # Launch core components of the rover software inside container
    gstreamer-cameras:
        build: .
        restart: unless-stopped
        environment:
            - 'true'
        privileged: true # this is intentional
        volumes:
            - '/run/udev:/run/udev:ro'
            - '/dev:/dev'
            - './config/config.yaml:/config.yaml'
            - '../certificates:/certificates'
        network_mode: host
