cameras:
  pci-0000:04:00.4-usb-0:1.3:1.0:
    name: front_platfrom
    protocol: h264
    width: 1920
    height: 1080
    framerate: 30
  pci-0000:04:00.4-usb-0:1.2:1.0:
    name: back_platform
    protocol: mjpeg
    width: 1280
    height: 720
    framerate: 30