name: Docker Ci

on:
  push:
    branches: 
      - master
      - refactor
  pull_request:
    branches: 
      - master
      - refactor

jobs:
  build:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: docker/steup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: "Dockerfile"