name: Deploy

on:
  push:
    branches:
      - main
      - release
    tags:
      - 'v*.*.*'
  
env:
  REGISTRY: ghcr.io
  IMAGE_CHANNEL: ${{ github.ref_type == 'tag' && github.ref || (github.ref == 'refs/heads/release' && 'stable' || 'nightly') }}
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  deploy:
    name: Build Container
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        id: push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_CHANNEL }}
          cache-from: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_CHANNEL }}

      # - name: Attest
      #   uses: actions/attest-build-provenance@v1
      #   with:
      #     subject-name: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_CHANNEL }}
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true